Berny\Bundle\FrontBundle\Entity\Url:
    type: entity
    table: url
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            unique: true
        shortUrl:
            type: string
            nullable: true
            unique: true
